brew "gh"
brew "go-task"
brew "mise"
brew "neovim"
brew "starship"
brew "tmux"

cask "1password"
cask "flux-app"
cask "font-sauce-code-pro-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
