# https://taskfile.dev

version: '3'

includes:
  mac: ./tasks/mac-defaults.yml
  symlink: ./tasks/symlink.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
