# https://taskfile.dev

version: '3'

includes:
  mac: ./tasks/mac-defaults.yml
  symlink: ./tasks/symlink.yml
  brew: ./tasks/brew.yml
  mise: ./tasks/mise.yml

tasks:
  default:
    cmd: task -l
    silent: true

  install:
    desc: Complete system setup - installs dependencies
    summary: |
      Performs a full system setup by
    cmds:
      - task: brew:install
      - task: mac:mac-defaults
      - task: symlink:install
      - task: mise:install
