# https://taskfile.dev

version: '3'

includes:
  mac: ./tasks/mac-defaults.yml
  symlink: ./tasks/symlink.yml
  brew: ./tasks/brew.yml
  mise: ./tasks/mise.yml

tasks:
  default:
    cmd: task -l
    silent: true
