# macOS defaults configuration tasks
# Converted from script/mac_defaults.sh

version: '3'

tasks:
  mac-defaults:
    desc: "Apply macOS defaults settings"
    deps: []
    cmds:
      - task: mac-defaults:general-ui
      - task: mac-defaults:trackpad-keyboard
      - task: mac-defaults:finder
      - task: mac-defaults:terminal
      - task: mac-defaults:activity-monitor
      - task: mac-defaults:restart-apps

  mac-defaults:general-ui:
    desc: "Configure general UI settings"
    internal: true
    cmds:
      - |
        echo "Use AirDrop over every interface. srsly this should be a default."
        defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
      - |
        echo "Expand save panel by default"
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
      - |
        echo "Expand print panel by default"
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
      - |
        echo "Save to disk (not to iCloud) by default"
        defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
      - |
        echo "Automatically quit printer app once the print jobs complete"
        defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
      - |
        echo "Disable the \"Are you sure you want to open this application?\" dialog"
        defaults write com.apple.LaunchServices LSQuarantine -bool false
      - |
        echo "Remove duplicates in the Open With menu (also see \`lscleanup\` alias)"
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
      - |
        echo "Reveal IP, hostname, OS, etc. when clicking clock in login window"
        sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

  mac-defaults:trackpad-keyboard:
    desc: "Configure trackpad and keyboard settings"
    internal: true
    cmds:
      - |
        echo "Disable press-and-hold for keys in favor of key repeat"
        defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
      - |
        echo "Set a blazingly fast keyboard repeat rate"
        defaults write NSGlobalDomain KeyRepeat -int 2
        defaults write NSGlobalDomain InitialKeyRepeat -int 15

  mac-defaults:finder:
    desc: "Configure Finder settings"
    internal: true
    cmds:
      - |
        echo "When performing a search, search the current folder by default"
        defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
      - |
        echo "Disable the warning when changing a file extension"
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
      - |
        echo "Avoid creating .DS_Store files on network volumes"
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
      - |
        echo "Show the ~/Library folder"
        chflags nohidden ~/Library

  mac-defaults:terminal:
    desc: "Configure Terminal/iTerm settings"
    internal: true
    cmds:
      - |
        echo "Don't display the annoying prompt when quitting iTerm"
        defaults write com.googlecode.iterm2 PromptOnQuit -bool false

  mac-defaults:activity-monitor:
    desc: "Configure Activity Monitor settings"
    internal: true
    cmds:
      - |
        echo "Show the main window when launching Activity Monitor"
        defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
      - |
        echo "Visualize CPU usage in the Activity Monitor Dock icon"
        defaults write com.apple.ActivityMonitor IconType -int 5
      - |
        echo "Show all processes in Activity Monitor"
        defaults write com.apple.ActivityMonitor ShowCategory -int 0
      - |
        echo "Sort Activity Monitor results by CPU usage"
        defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
        defaults write com.apple.ActivityMonitor SortDirection -int 0

  mac-defaults:restart-apps:
    desc: "Restart applications to apply changes"
    internal: true
    cmds:
      - |
        echo "Killing a bunch of apps. Don't be alarmed"
        for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
                "Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
                    "Terminal" "Transmission" "Twitter" "iCal"; do
            killall "${app}" > /dev/null 2>&1 || true
        done
        echo "Done. Note that some of these changes require a logout/restart to take effect."
