# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

tasks:
  install:
    desc: Install the try-cli Ruby gem
    cmds:
      - gem install try-cli
    status:
      - which try
