tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "neovim"
brew "tmux"
brew "font-sauce-code-pro-nerd-font"

cask "iterm2"
cask "google-chrome"
cask "raycast"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
